PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/68a2727c1201b81b9818bce3b253e5226e47f3b7

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/1c488eb864ff657474f97c342ec5c8fcd2bcb7fd) in current PX4/master (1141cfa7c6bea43be9ec1efa53334662143f0073)
https://github.com/PX4/NuttX/compare/1c488eb864ff657474f97c342ec5c8fcd2bcb7fd...68a2727c1201b81b9818bce3b253e5226e47f3b7

68a2727c12 (HEAD, origin/master) arch/sim: Extend the heap size to 64MB
411f5d591a sched: Fix undefined reference to 'sched_cpu_count'
ba3f12c93f libc: Implement popcount/popcountl/popcountll
657d1c9fdc Add and fix CSR macros listed in RISC-V spec V1.10. Add csr operatiing macros.
5498f72fa5 input: Q10 BlackBerry Keyboard from Solder Party
366e8afdb1 net/usrsock: fix outputted function name in debug prints
64e2f102ac xtensa/esp32: Add power management of force-sleep
29030557ff sched: Fix nuttx typo
b2b7541d59 nuttx/wireless: fix nxstyle warning
9e45d6e88e nuttx/wireless: add wireless event member length helper

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/df389bc3322af9e7004a855c82a10daff978c4ec

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/3edfb4a3acc0d01838d01367c2f5f7da9b1db57f) in current PX4/master (1141cfa7c6bea43be9ec1efa53334662143f0073)
https://github.com/PX4/NuttX-apps/compare/3edfb4a3acc0d01838d01367c2f5f7da9b1db57f...df389bc3322af9e7004a855c82a10daff978c4ec

df389bc3 (HEAD -> master, origin/master) apps/Application.mk: fix compile assmbely error
e8a353af netutils: dhcpc: Fix dhcpc.c
d635fcb2 application.mk: fix multi MAINSRC match suffix in single Makefile
3c4089ef apps/MAKE: Add register staging to context
3061dbf2 wireless/wapi: add option to associate with bssid
a0f6b14c wireless/wapi: add scan partial channel support
77aa0e89 netutils/dhcpc: try to get the host name via syscall first
40f559bf wireless/wapi: ignore the fail case
1b9c307e make/import: lost ARCHCPUFLAGS in cxx command line
69956020 interpreters/wamr: Add missing options